liga = set(["REAL MADRID", "BARCELONA", "MANCHESTER UNITED", "BAYERN MUNICH", "JUVENTUS", "LIVERPOOL", "MANCHESTER CITY", "ARSENAL", "CHELSEA", "PARIS SAINT GERMAIN"])
liga_2 = set(["TOTTENHAM", "BORUSSIA DORTMUND", "AC MILAN", "INTER MILAN", "ATLETICO MADRID", "AJAX", "PORTO", "AS ROMA", "OLYMPIQUE DE MARSEILLE", "GALATASARAY"])
liga_3 = set(["REAL MADRID", "BARCELONA", "ATLETICO MADRID", "MANCHESTER UNITED", "LIVERPOOL", "ARSENAL", "CHELSEA", "TOTTENHAM", "AJAX", "MANCHESTER CITY"])
liga_4 = set(["BORUSSIA DORTMUND", "BAYERN MUNICH", "PARIS SAINT GERMAIN", "INTER MILAN", "PORTO", "AS ROMA", "OLYMPIQUE DE MARSEILLE", "GALATASARAY", "JUVENTUS", "AC MILAN"])

print(liga, liga_2, liga_3, liga_4)